# Generated by Django 5.2.8 on 2025-11-23 22:59

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único da categoria",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome da categoria (ex: Concurso de Cosplay)",
                        max_length=100,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL amigável (ex: concurso-cosplay)",
                        max_length=120,
                        unique=True,
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição detalhada da categoria",
                        null=True,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("evento", "Evento"), ("colecao", "Coleção")],
                        help_text="Esta categoria é para eventos ou coleções?",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Data de criação do registro"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "db_table": "categorias",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Título do evento (ex: Anima Luanda 2025)",
                        max_length=200,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL amigável do evento", max_length=250, unique=True
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True, help_text="Descrição completa do evento", null=True
                    ),
                ),
                (
                    "data_inicio",
                    models.DateTimeField(help_text="Data e hora de início do evento"),
                ),
                (
                    "data_fim",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e hora de término (opcional para eventos de 1 dia)",  # noqa: E501
                        null=True,
                    ),
                ),
                (
                    "local",
                    models.CharField(
                        blank=True,
                        help_text="Local onde ocorre o evento (ex: Centro de Convenções de Talatona)",  # noqa: E501
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "tipo_evento",
                    models.CharField(
                        choices=[
                            ("concurso", "Concurso de Cosplay"),
                            ("exposicao", "Exposição"),
                            ("workshop", "Workshop"),
                            ("cobertura", "Cobertura de Evento"),
                        ],
                        help_text="Qual o tipo deste evento?",
                        max_length=20,
                    ),
                ),
                (
                    "abrangencia",
                    models.CharField(
                        choices=[
                            ("nacional", "Nacional"),
                            ("internacional", "Internacional"),
                        ],
                        default="nacional",
                        help_text="Abrangência do evento",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("publicado", "Publicado"),
                            ("finalizado", "Finalizado"),
                        ],
                        default="rascunho",
                        help_text="Status atual do evento",
                        max_length=20,
                    ),
                ),
                (
                    "imagem_destaque",
                    models.URLField(
                        blank=True,
                        help_text="URL da imagem de capa do evento (Cloudinary)",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        help_text="Categoria deste evento",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eventos",
                        to="events.categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "db_table": "eventos",
                "ordering": ["-data_inicio"],
            },
        ),
        migrations.CreateModel(
            name="EventoParceiro",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo_apoio",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Patrocínio Gold, Apoio de Mídia, etc",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.evento"
                    ),
                ),
            ],
            options={
                "verbose_name": "Parceiro do Evento",
                "verbose_name_plural": "Parceiros dos Eventos",
                "db_table": "evento_parceiro",
            },
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email para receber a newsletter",
                        max_length=150,
                        unique=True,
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True,
                        help_text="Nome do assinante (opcional)",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Deseja receber emails? (permite descadastrar sem apagar)",  # noqa: E501
                    ),
                ),
                (
                    "data_inscricao",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Quando se inscreveu"
                    ),
                ),
                (
                    "data_confirmacao",
                    models.DateTimeField(
                        blank=True,
                        help_text="Quando confirmou o email (double opt-in)",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Assinante da Newsletter",
                "verbose_name_plural": "Assinantes da Newsletter",
                "db_table": "newsletter",
                "ordering": ["-data_inscricao"],
                "indexes": [
                    models.Index(fields=["email"], name="newsletter_email_35bdf0_idx"),
                    models.Index(fields=["ativo"], name="newsletter_ativo_12f354_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Parceiro",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome da empresa/instituição parceira", max_length=150
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("patrocinador", "Patrocinador"),
                            ("apoio", "Apoio"),
                            ("midia", "Mídia Parceira"),
                            ("institucional", "Parceiro Institucional"),
                        ],
                        help_text="Tipo de parceria",
                        max_length=20,
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(
                        blank=True,
                        help_text="URL do logo (Cloudinary)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "site",
                    models.URLField(
                        blank=True, help_text="Site oficial do parceiro", null=True
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição sobre o parceiro e a parceria",
                        null=True,
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True, help_text="Parceiro ativo no momento?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "eventos",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Eventos que este parceiro apoia",
                        related_name="parceiros",
                        through="events.EventoParceiro",
                        to="events.evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parceiro",
                "verbose_name_plural": "Parceiros",
                "db_table": "parceiros",
                "ordering": ["nome"],
            },
        ),
        migrations.AddField(
            model_name="eventoparceiro",
            name="parceiro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="events.parceiro"
            ),
        ),
        migrations.AddIndex(
            model_name="evento",
            index=models.Index(fields=["slug"], name="eventos_slug_3b493c_idx"),
        ),
        migrations.AddIndex(
            model_name="evento",
            index=models.Index(
                fields=["data_inicio"], name="eventos_data_in_1deeb1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evento",
            index=models.Index(fields=["status"], name="eventos_status_5c29c9_idx"),
        ),
        migrations.AddIndex(
            model_name="parceiro",
            index=models.Index(fields=["tipo"], name="parceiros_tipo_4f2c13_idx"),
        ),
        migrations.AddIndex(
            model_name="parceiro",
            index=models.Index(fields=["ativo"], name="parceiros_ativo_63bdb2_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="eventoparceiro",
            unique_together={("evento", "parceiro")},
        ),
    ]
