# Generated by Django 5.2.8 on 2025-11-23 22:59

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cosplayer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome real do cosplayer", max_length=150
                    ),
                ),
                (
                    "nome_artistico",
                    models.CharField(
                        blank=True,
                        help_text="Nome artístico ou apelido usado no cosplay",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL amigável do perfil", max_length=200, unique=True
                    ),
                ),
                (
                    "biografia",
                    models.TextField(
                        blank=True,
                        help_text="Biografia e história no cosplay",
                        null=True,
                    ),
                ),
                (
                    "foto_perfil",
                    models.URLField(
                        blank=True,
                        help_text="URL da foto de perfil (Cloudinary)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "instagram",
                    models.CharField(
                        blank=True,
                        help_text="Username do Instagram (sem @)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "facebook",
                    models.CharField(
                        blank=True,
                        help_text="Username ou URL do Facebook",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "tiktok",
                    models.CharField(
                        blank=True,
                        help_text="Username do TikTok (sem @)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cosplayer",
                "verbose_name_plural": "Cosplayers",
                "db_table": "cosplayers",
                "ordering": ["nome"],
                "indexes": [
                    models.Index(fields=["slug"], name="cosplayers_slug_4b143c_idx"),
                    models.Index(fields=["nome"], name="cosplayers_nome_076613_idx"),
                ],
            },
        ),
    ]
