# Generated by Django 5.2.8 on 2025-11-23 23:27

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cosplayers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cosplayer",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False,
                help_text="URL amigável gerada automaticamente do nome",
                max_length=200,
                populate_from="nome",
                unique=True,
            ),
        ),
    ]
