# Generated by Django 5.2.8 on 2025-11-23 22:59

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cosplay_collections", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColecaoMidia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0, help_text="Ordem de exibição desta mídia na coleção"
                    ),
                ),
                (
                    "descricao_contexto",
                    models.TextField(
                        blank=True,
                        help_text="Contexto específico desta mídia nesta coleção",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "colecao",
                    models.ForeignKey(
                        help_text="Coleção que contém a mídia",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cosplay_collections.colecao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mídia da Coleção",
                "verbose_name_plural": "Mídias das Coleções",
                "db_table": "colecao_midia",
                "ordering": ["colecao", "ordem"],
            },
        ),
        migrations.CreateModel(
            name="Midia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        blank=True,
                        help_text="Título ou legenda da mídia",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição detalhada ou contexto da foto/vídeo",
                        null=True,
                    ),
                ),
                (
                    "arquivo_url",
                    models.URLField(
                        help_text="URL completa do arquivo hospedado no Cloudinary",
                        max_length=500,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("imagem", "Imagem"), ("video", "Vídeo")],
                        default="imagem",
                        help_text="Tipo de arquivo",
                        max_length=10,
                    ),
                ),
                (
                    "formato",
                    models.CharField(
                        blank=True,
                        help_text="Extensão do arquivo (jpg, png, mp4, etc)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "tamanho_kb",
                    models.IntegerField(
                        blank=True,
                        help_text="Tamanho do arquivo em kilobytes",
                        null=True,
                    ),
                ),
                (
                    "largura",
                    models.IntegerField(
                        blank=True,
                        help_text="Largura em pixels (para imagens/vídeos)",
                        null=True,
                    ),
                ),
                (
                    "altura",
                    models.IntegerField(
                        blank=True,
                        help_text="Altura em pixels (para imagens/vídeos)",
                        null=True,
                    ),
                ),
                (
                    "creditos_fotografo",
                    models.CharField(
                        blank=True,
                        help_text="Nome do fotógrafo/videomaker responsável",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "data_captura",
                    models.DateField(
                        blank=True,
                        help_text="Data em que a foto/vídeo foi capturado",
                        null=True,
                    ),
                ),
                (
                    "destaque",
                    models.BooleanField(default=False, help_text="Mídia em destaque?"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "colecoes",
                    models.ManyToManyField(
                        help_text="Coleções que contêm esta mídia",
                        related_name="midias",
                        through="media_files.ColecaoMidia",
                        to="cosplay_collections.colecao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mídia",
                "verbose_name_plural": "Mídias",
                "db_table": "midias",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="colecaomidia",
            name="midia",
            field=models.ForeignKey(
                help_text="Mídia incluída na coleção",
                on_delete=django.db.models.deletion.CASCADE,
                to="media_files.midia",
            ),
        ),
        migrations.AddIndex(
            model_name="midia",
            index=models.Index(fields=["tipo"], name="midias_tipo_c4d1bc_idx"),
        ),
        migrations.AddIndex(
            model_name="midia",
            index=models.Index(
                fields=["data_captura"], name="midias_data_ca_04c83a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="midia",
            index=models.Index(fields=["destaque"], name="midias_destaqu_d4410b_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="colecaomidia",
            unique_together={("colecao", "midia")},
        ),
    ]
