# Generated by Django 5.2.8 on 2025-11-23 22:59

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cosplayers", "0001_initial"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Colecao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Título da coleção (ex: Especial Anima Luanda 2025)",
                        max_length=200,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL amigável da coleção", max_length=250, unique=True
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição da coleção e contexto",
                        null=True,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("cosplayer", "Ensaio de Cosplayer"),
                            ("evento", "Cobertura de Evento"),
                            ("tematica", "Coleção Temática"),
                        ],
                        help_text="Tipo desta coleção",
                        max_length=20,
                    ),
                ),
                (
                    "data_producao",
                    models.DateField(
                        blank=True,
                        help_text="Data em que a produção foi realizada",
                        null=True,
                    ),
                ),
                (
                    "destaque",
                    models.BooleanField(
                        default=False, help_text="Exibir como destaque no site?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cosplayer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cosplayer principal (se for ensaio individual)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="colecoes",
                        to="cosplayers.cosplayer",
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        blank=True,
                        help_text="Evento relacionado (se for cobertura de evento)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="colecoes",
                        to="events.evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coleção",
                "verbose_name_plural": "Coleções",
                "db_table": "colecoes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="colecoes_slug_4fb53e_idx"),
                    models.Index(fields=["tipo"], name="colecoes_tipo_31d393_idx"),
                    models.Index(
                        fields=["destaque"], name="colecoes_destaqu_c8fa17_idx"
                    ),
                ],
            },
        ),
    ]
